# Generated by Django 5.0.6 on 2024-08-07 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('subcategory_desc', models.TextField(blank=True, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('images', models.ImageField(upload_to='images')),
                ('SubCategory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brand.category')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.subcategory')),
            ],
        ),
    ]
