# Generated by Django 5.0.6 on 2024-08-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_product_subcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
